---
- when: >-
    vars.anarchy_subject.vars.job_vars.__meta__.aws_sandboxed | default(false)
    or
    vars.anarchy_governor.vars.job_vars.__meta__.aws_sandboxed | default(false)

  block:

    - include_tasks: pre_checks.yaml

    - name: Get sandbox when it needs to be passed to tower job
      when:
        # Do nothing unless executing an action
        - anarchy_action_config_name is defined
        # Check action gets status of tower jobs, but does not need sandbox info
        - anarchy_action_config_name != 'check'
        # Callbacks from tower jobs and do not need sandbox info for processing
        - anarchy_action_callback_name is not defined
      include_tasks: get.yaml

    - name: Mark sandbox for cleanup (destroy complete)
      when:
        - anarchy_action_config_name is defined
        - anarchy_action_config_name == 'destroy'
        - anarchy_action_callback_name is defined
        - anarchy_action_callback_name == 'complete'
      include_tasks: release.yaml
