---
- when: >-
    vars.anarchy_subject.vars.job_vars.__meta__.aws_sandboxed | default(false)
    or
    vars.anarchy_governor.vars.job_vars.__meta__.aws_sandboxed | default(false)

  block:

    - include_tasks: pre_checks.yaml

    - name: Get sandbox when it needs to be passed to tower job
      when:
        # Do nothing unless executing an action
        - anarchy_action_config_name is defined
        # Callbacks from tower jobs and do not need sandbox info for processing
        - anarchy_action_callback_name is not defined
      include_tasks: get.yaml

    - name: Mark sandbox for cleanup (destroy complete, failed, or disabled)
      when: >-
        (
          'destroy' == anarchy_action_config_name | default('')
          and
          'complete' == anarchy_action_callback_name | default('')
        ) or
        'destroy-error' == current_state | default('') or
        'destroy-failed' == current_state | default('') or
        'destroy-canceled' == current_state | default('') or
        __meta__.deployer.actions.destroy.disable | default(false) | bool
      include_tasks: release.yaml

    - name: Complete deletion anarchy subject on destroy failure
      when: >-
        'destroy-error' == current_state | default('') or
        'destroy-failed' == current_state | default('') or
        'destroy-canceled' == current_state | default('')
      anarchy_subject_delete:
        remove_finalizers: true
