---
- when: >-
    vars.anarchy_subject.vars.job_vars.__meta__.aws_sandboxed | default(false)
    or
    vars.anarchy_governor.vars.job_vars.__meta__.aws_sandboxed | default(false)

  block:

    - include_tasks: pre_checks.yaml

    - name: Get sandbox (always but no callbacks)
      when:
        - anarchy_action_config_name is defined
        - anarchy_action_callback_name is not defined
      include_tasks: get.yaml

    - name: Mark sandbox for cleanup (destroy complete)
      when:
        - anarchy_action_config_name is defined
        - anarchy_action_config_name == 'destroy'
        - anarchy_action_callback_name is defined
        - anarchy_action_callback_name == 'complete'
      include_tasks: release.yaml
