---
- name: Ensure mandatory variables are set
  assert:
    that: "{{ check.that }}"
    fail_msg: "{{ check.msg }}"
    quiet: true
  loop_control:
    loop_var: check
    label: "{{ check.msg }}"
  loop:
    - msg: anarchy variables must be defined, are we running in Anarchy?
      that:
      # Check for anarchy_governor and anarchy_subject, but be careful not to trigger template
      # evaluation. These often will contain variable references that cannot be resolved by
      # anarchy but will later be resolved within the deployer job.
      - vars.anarchy_governor is defined
      - vars.anarchy_subject is defined
      # The anarchy_subject_name should always be availble
      - anarchy_subject_name is defined
      # When processing an action the callback url and token must be defined
      - anarchy_action_callback_token is defined or anarchy_action_name is not defined
      - anarchy_action_callback_url is defined or anarchy_action_name is not defined
      # The anarchy_action_config_name is the name of the type of action configured in the governor
      # and must be defined unless processing an event
      - anarchy_event_name is defined or anarchy_action_config_name is defined
      # The anarchy_action_name is the name of the type of action resource and must be defined
      # unless processing an event
      - anarchy_event_name is defined or anarchy_action_name is defined
      # The anarchy_run_timestamp is the YYYY-MM-DDTHH:MM:SSZ format timestamp string of the run
      # start time. This is useful anarchy does not gather facts and so ansible_date_time is not
      # available.
    - anarchy_run_timestamp is defined

    - msg: Variable guid is not defined
      that: guid is defined and guid != ''

    - msg: Variable env_type is not defined
      that: env_type is defined and env_type != ''

    - msg: Variable pool_region is not defined
      that: pool_region is defined and pool_region != ''

    - msg: Variable pool_manager_aws_access_key_id is not defined
      that:
        - pool_manager_aws_access_key_id is defined
        - pool_manager_aws_access_key_id != ''

    - msg: Variable pool_manager_aws_secret_access_key is not defined
      that:
        - pool_manager_aws_secret_access_key is defined
        - pool_manager_aws_secret_access_key != ''

    - msg: Variable pool_manager_vault_password is not defined
      that:
        - pool_manager_vault_password is defined
        - pool_manager_vault_password != ''

    - msg: email and student name can't be both undefined
      that: >-
        email is defined and email != ''
        or
        student_name is defined and student_name != ''
