---
- when: sandbox_api_login_token is defined
  block:
    - include_tasks: sandbox_api_login.yaml
    - include_tasks: sandbox_api_release.yaml

# If placement was not found, it's safe to run legacy code to mark to cleanup
# any account which match uuid.
- when: r_del.status == 404
  include_tasks: legacy_release.yaml
